# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('description', models.TextField(max_length=1000)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
